name: ğŸš€ Build
on:
  push:
    branches:
      - main
      - dev
  pull_request: {}

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: â¬£ ESLint
    runs-on: ${{ vars.RUNNER || 'ubuntu-latest' }}
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: ğŸ”¬ Lint
        run: npm run lint

  typecheck:
    name: Ê¦ TypeScript
    runs-on: ${{ vars.RUNNER || 'ubuntu-latest' }}
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: ğŸ” Type check
        run: npm run typecheck --if-present

  cypress:
    name: âš«ï¸ Cypress
    runs-on: ${{ vars.RUNNER || 'ubuntu-latest' }}
    env:
      ENABLE_STRIPE_TESTING: ${{ vars.ENABLE_STRIPE_TESTING }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      STRIPE_DEVICE_NAME: "GitHub Actions"

    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Environment variables
        uses: aarcangeli/load-dotenv@v1.0.0
        with:
          filenames: |
            .env.test
          quiet: true
          if-file-not-found: error

      - name: Cache firebase emulators
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('/home/runner/.cache/firebase/emulators/**') }}

      - name: Cache Cypress Binary
        id: cache-cypress-binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: binary-${{ hashFiles('package-lock.json') }}

      - name: ğŸ” Test
        run: npm test

      - name: Archive test screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: cypress/screenshots
        if: ${{ failure() }}